version: '3'

services:
  database:
    container_name: postgresql
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./guestbook:/var/www/symfony
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - '8081:80'
    volumes:
      - ./guestbook:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
volumes:
  postgresql_data: