version: '3'

services:
  database:
    container_name: postgresql_${DIRECTORY}
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
  php:
    container_name: php_${DIRECTORY}
    build:
      context: conf/php
    volumes:
      - ./${DIRECTORY}:/var/www/symfony
    ports:
      - ${PHP_PORTS}
    depends_on:
      - database
  nginx:
    container_name: nginx_${DIRECTORY}
    image: nginx:stable
    ports:
      - ${NGINX_PORTS}
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./${DIRECTORY}/public:/var/www/symfony/public
    depends_on:
      - php

volumes:
  postgresql_data:



