version: '3'

services:
  app:
    container_name: app
    image: luckyraul/docker-dummy
    volumes:
      - ./guestbook:/var/www/public
  database:
    container_name: postgresql
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
  php:
    container_name: php
    build:
      context: conf/php
    ports:
      - '9000:9000'
    volumes:
      - type: volume
        source: app
        target: /var/www/symfony
      - "/usr/local/var/www/projects/guestbook_project/guestbook:/var/www/symfony:rwx"
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - '8081:80'
    volumes:
      - "./conf/nginx/:/etc/nginx/sites-enabled/"
    depends_on:
      - php
      - database
volumes:
  postgresql_data:
  app:


